import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync, unlinkSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';

// Splits the single-file SQL guides (sql-guide.md, sql-guide-es.md) into one
// file per section under sections/<lang>/. The single files are the source of
// truth; everything under sections/ is generated.

// File names are fixed by position, so renaming a section keeps its links.
export const SLUGS = [
  '01-ddl', '02-dml', '03-select', '04-where', '05-order-by-limit',
  '06-group-by', '07-joins', '08-subqueries', '09-set-operations', '10-functions',
  '11-indexes-views', '12-transactions', '13-stored-procedures', '14-null', '15-constraints',
  '16-normalization', '17-window-functions', '18-upsert', '19-triggers', '20-permissions',
  '21-recursive-cte', '22-indexes-explain', '23-isolation-acid', '24-exercises', '25-cheat-sheet',
];

// Splits text into lines, each tagged with whether it sits inside a ``` fence.
// Fence delimiter lines themselves count as inside.
function scanLines(text) {
  let inFence = false;
  return text.replaceAll('\r\n', '\n').split('\n').map((line) => {
    const isFence = line.startsWith('```');
    if (isFence) inFence = !inFence;
    return { line, code: inFence || isFence };
  });
}

// Drops blank lines and `---` separators from both ends.
function trimEdges(lines) {
  const isEdge = (l) => !l.code && (l.line.trim() === '' || l.line === '---');
  let start = 0;
  let end = lines.length;
  while (start < end && isEdge(lines[start])) start++;
  while (end > start && isEdge(lines[end - 1])) end--;
  return lines.slice(start, end);
}

export function parseGuide(markdown, sourceName) {
  const lines = scanLines(markdown);
  const headings = lines
    .map((l, i) => (!l.code && l.line.startsWith('## ') ? i : -1))
    .filter((i) => i >= 0);
  const first = headings.findIndex((i) => lines[i].line.startsWith('## 1. '));
  const starts = first < 0 ? [] : headings.slice(first);

  if (starts.length !== SLUGS.length) {
    throw new Error(`Expected ${SLUGS.length} sections in ${sourceName}, found ${starts.length}`);
  }

  const intro = trimEdges(lines.slice(0, starts[0])).map((l) => l.line).join('\n');

  const sections = starts.map((start, n) => {
    const slice = lines
      .slice(start, starts[n + 1] ?? lines.length)
      .filter((l) => l.code || !/^# /.test(l.line));      // group H1s like "# Going further"
    const body = trimEdges(slice)
      .map((l) => (!l.code && /^#{2,6} /.test(l.line) ? l.line.slice(1) : l.line))
      .join('\n');
    return { slug: SLUGS[n], title: lines[start].line.slice(3), body };
  });

  return { intro, sections };
}

export const LANGS = {
  en: {
    source: 'sql-guide.md', other: 'es', flag: '🇪🇸', otherName: 'Español',
    prev: 'Previous', next: 'Next', index: 'Index', single: 'Prefer a single file?',
  },
  es: {
    source: 'sql-guide-es.md', other: 'en', flag: '🇬🇧', otherName: 'English',
    prev: 'Anterior', next: 'Siguiente', index: 'Índice', single: '¿Prefieres un solo fichero?',
  },
};

const header = (source) =>
  `<!-- Generated by scripts/split-guide.mjs from ${source}. Do not edit by hand. -->`;

function renderNav(lang, n) {
  const t = LANGS[lang];
  const parts = [];
  if (n > 0) parts.push(`[← ${t.prev}](${SLUGS[n - 1]}.md)`);
  parts.push(`[${t.index}](README.md)`);
  if (n < SLUGS.length - 1) parts.push(`[${t.next} →](${SLUGS[n + 1]}.md)`);
  parts.push(`${t.flag} [${t.otherName}](../${t.other}/${SLUGS[n]}.md)`);
  return parts.join(' · ');
}

// The guide's intro, with the table of contents turned into links to the
// section files and the language link pointing at the other language's index.
function renderIndex(lang, intro, sections) {
  const t = LANGS[lang];
  const lines = scanLines(intro);
  // Drop the guide's "also available per section" line (and the blank after it):
  // inside sections/ it would link to itself.
  const self = lines.findIndex((l) => !l.code && l.line.includes('](sections/'));
  if (self >= 0) lines.splice(self, lines[self + 1]?.line === '' ? 2 : 1);
  const body = lines.map(({ line, code }) => {
    if (code) return line;
    const toc = line.match(/^(\d+)\. (.+)$/);
    if (toc && toc[1] >= 1 && toc[1] <= SLUGS.length - 1) {
      return `${toc[1]}. [${toc[2]}](${SLUGS[toc[1] - 1]}.md)`;
    }
    return line.replace(/\]\(sql-guide(-es)?\.md\)/, `](../${t.other}/README.md)`);
  });
  const cheatSheet = sections[SLUGS.length - 1];
  return [
    header(t.source), '', ...body, '',
    `[${cheatSheet.title}](${cheatSheet.slug}.md)`, '',
    `${t.single} [${t.source}](../../${t.source})`, '',
  ].join('\n');
}

export function renderAll(guides) {
  const files = new Map();
  for (const lang of Object.keys(LANGS)) {
    const { source } = LANGS[lang];
    const { intro, sections } = parseGuide(guides[lang], source);
    const dir = `sections/${lang}`;
    files.set(`${dir}/README.md`, renderIndex(lang, intro, sections));
    sections.forEach((s, n) => {
      const nav = renderNav(lang, n);
      files.set(`${dir}/${s.slug}.md`, [header(source), '', nav, '', s.body, '', '---', '', nav, ''].join('\n'));
    });
  }
  return files;
}

// Generated .md files currently on disk under sections/<lang>/, as repo-relative paths.
function existingFiles(root) {
  return Object.keys(LANGS).flatMap((lang) => {
    const dir = path.join(root, 'sections', lang);
    if (!existsSync(dir)) return [];
    return readdirSync(dir).filter((f) => f.endsWith('.md')).map((f) => `sections/${lang}/${f}`);
  });
}

export function writeFiles(files, root) {
  const removed = existingFiles(root).filter((f) => !files.has(f)).sort();
  for (const f of removed) unlinkSync(path.join(root, f));
  for (const [file, content] of files) {
    mkdirSync(path.dirname(path.join(root, file)), { recursive: true });
    writeFileSync(path.join(root, file), content);
  }
  return { written: [...files.keys()], removed };
}

export function checkFiles(files, root) {
  const stale = [];
  const missing = [];
  for (const [file, content] of files) {
    const target = path.join(root, file);
    if (!existsSync(target)) missing.push(file);
    else if (readFileSync(target, 'utf8').replaceAll('\r\n', '\n') !== content) stale.push(file);
  }
  const extra = existingFiles(root).filter((f) => !files.has(f));
  return { stale: stale.sort(), missing: missing.sort(), extra: extra.sort() };
}

function main(args) {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
  const guides = Object.fromEntries(
    Object.entries(LANGS).map(([lang, t]) => [lang, readFileSync(path.join(root, t.source), 'utf8')]),
  );
  const files = renderAll(guides);

  if (args.includes('--check')) {
    const result = checkFiles(files, root);
    const problems = Object.entries(result).flatMap(([kind, list]) => list.map((f) => `${kind}: ${f}`));
    if (problems.length) {
      console.error(`sections/ is out of date. Run: npm run build:sections\n${problems.join('\n')}`);
      process.exit(1);
    }
    console.log('sections/ is up to date');
    return;
  }

  const { written, removed } = writeFiles(files, root);
  console.log(`Wrote ${written.length} files, removed ${removed.length}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main(process.argv.slice(2));
}
