import { readFileSync, writeFileSync, mkdirSync, readdirSync, existsSync, unlinkSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import path from 'node:path';

// Splits the single-file SQL guides (sql-guide.md, sql-guide-es.md) into one
// file per section under sections/<lang>/. The single files are the source of
// truth; everything under sections/ is generated.

// File names are fixed by position, so renaming a section keeps its links.
export const SLUGS = [
  '01-ddl', '02-dml', '03-select', '04-where', '05-order-by-limit',
  '06-group-by', '07-joins', '08-subqueries', '09-set-operations', '10-functions',
  '11-indexes-views', '12-transactions', '13-stored-procedures', '14-null', '15-constraints',
  '16-normalization', '17-window-functions', '18-upsert', '19-triggers', '20-permissions',
  '21-recursive-cte', '22-indexes-explain', '23-isolation-acid', '24-exercises', '25-cheat-sheet',
];

// What each position's title must match, in English or Spanish. Catches
// sections that were moved without updating SLUGS, which would otherwise give
// files whose name doesn't match their content.
export const TITLE_HINTS = [
  /DDL/, /DML/, /SELECT/, /WHERE/, /ORDER BY/,
  /GROUP BY/, /join/i, /Subquer|Subconsultas/, /UNION/, /Useful functions|Funciones útiles/,
  /views|vistas/, /Transactions ·|Transacciones ·/, /procedures|procedimientos/i, /NULL/, /Constraints|Restricciones/,
  /Normali/, /Window|ventana/, /UPSERT/, /Triggers/, /permissions|permisos/,
  /recursive|recursivas/i, /EXPLAIN/, /ACID/, /Exercises|Ejercicios/, /Cheat sheet|Chuleta/,
];

// H1s allowed between sections; they group sections in the single file.
const GROUP_HEADINGS = ['# Going further', '# Ampliación'];

// Splits text into lines, each tagged with whether it sits inside a ``` fence.
// Fence delimiter lines themselves count as inside.
function scanLines(text) {
  let inFence = false;
  return text.replaceAll('\r\n', '\n').split('\n').map((line) => {
    const isFence = line.startsWith('```');
    if (isFence) inFence = !inFence;
    return { line, code: inFence || isFence };
  });
}

// Drops blank lines and `---` separators from both ends.
function trimEdges(lines) {
  const isEdge = (l) => !l.code && (l.line.trim() === '' || l.line === '---');
  let start = 0;
  let end = lines.length;
  while (start < end && isEdge(lines[start])) start++;
  while (end > start && isEdge(lines[end - 1])) end--;
  return lines.slice(start, end);
}

export function parseGuide(markdown, sourceName) {
  const lines = scanLines(markdown);
  const headings = lines
    .map((l, i) => (!l.code && l.line.startsWith('## ') ? i : -1))
    .filter((i) => i >= 0);
  const first = headings.findIndex((i) => lines[i].line.startsWith('## 1. '));
  const starts = first < 0 ? [] : headings.slice(first);

  if (starts.length !== SLUGS.length) {
    throw new Error(`Expected ${SLUGS.length} sections in ${sourceName}, found ${starts.length}`);
  }

  const intro = trimEdges(lines.slice(0, starts[0])).map((l) => l.line).join('\n');

  const sections = starts.map((start, n) => {
    const title = lines[start].line.slice(3);
    if (!TITLE_HINTS[n].test(title)) {
      throw new Error(
        `Section ${n + 1} in ${sourceName} is "${title}", which doesn't look like ${SLUGS[n]}. ` +
        'If sections were reordered, update SLUGS and TITLE_HINTS in scripts/split-guide.mjs.',
      );
    }
    const slice = lines.slice(start, starts[n + 1] ?? lines.length);
    const stray = slice.find((l) => !l.code && /^# /.test(l.line) && !GROUP_HEADINGS.includes(l.line));
    if (stray) throw new Error(`Unexpected H1 "${stray.line}" in ${sourceName}, section ${n + 1}`);
    const body = trimEdges(slice.filter((l) => l.code || !GROUP_HEADINGS.includes(l.line)))
      .map((l) => (!l.code && /^#{2,6} /.test(l.line) ? l.line.slice(1) : l.line))
      .join('\n');
    return { slug: SLUGS[n], title, body };
  });

  return { intro, sections };
}

export const LANGS = {
  en: {
    source: 'sql-guide.md', other: 'es', flag: '🇪🇸', otherName: 'Español',
    prev: 'Previous', next: 'Next', index: 'Index', single: 'Prefer a single file?',
    tables: 'Examples use the `customers` and `orders` tables described in the [index](README.md).',
  },
  es: {
    source: 'sql-guide-es.md', other: 'en', flag: '🇬🇧', otherName: 'English',
    prev: 'Anterior', next: 'Siguiente', index: 'Índice', single: '¿Prefieres un solo fichero?',
    tables: 'Los ejemplos usan las tablas `clientes` y `pedidos` descritas en el [índice](README.md).',
  },
};

const header = (source) =>
  `<!-- Generated by scripts/split-guide.mjs from ${source}. Do not edit by hand. -->`;

function renderNav(lang, n) {
  const t = LANGS[lang];
  const parts = [];
  if (n > 0) parts.push(`[← ${t.prev}](${SLUGS[n - 1]}.md)`);
  parts.push(`[${t.index}](README.md)`);
  if (n < SLUGS.length - 1) parts.push(`[${t.next} →](${SLUGS[n + 1]}.md)`);
  parts.push(`${t.flag} [${t.otherName}](../${t.other}/${SLUGS[n]}.md)`);
  return parts.join(' · ');
}

// The guide's intro, with the table of contents turned into links to the
// section files and the language link pointing at the other language's index.
function renderIndex(lang, intro, sections) {
  const t = LANGS[lang];
  const lines = scanLines(intro);
  // Drop the guide's "also available per section" line (and the blank after it):
  // inside sections/ it would link to itself.
  const self = lines.findIndex((l) => !l.code && l.line.includes('](sections/'));
  if (self >= 0) lines.splice(self, lines[self + 1]?.line === '' ? 2 : 1);
  const cheatSheet = sections[SLUGS.length - 1];
  const body = lines.map(({ line, code }) => {
    if (code) return line;
    // Table of contents lines end with level tags, e.g. "7. JOINs · 🟡 ⭐⭐⭐".
    const toc = line.match(/^(\d+)\. (.+ · [🟢🟡🔴].*)$/u);
    if (toc && toc[1] >= 1 && toc[1] <= SLUGS.length - 1) {
      const link = `${toc[1]}. [${toc[2]}](${SLUGS[toc[1] - 1]}.md)`;
      // The cheat sheet isn't numbered in the guide; list it right after the last section.
      if (Number(toc[1]) !== SLUGS.length - 1) return link;
      return `${link}\n\n[${cheatSheet.title}](${cheatSheet.slug}.md)`;
    }
    return line.replace(/\]\(sql-guide(-es)?\.md\)/, `](../${t.other}/README.md)`);
  });
  return [
    header(t.source), '', ...body, '',
    `${t.single} [${t.source}](../../${t.source})`, '',
  ].join('\n');
}

export function renderAll(guides) {
  const files = new Map();
  for (const lang of Object.keys(LANGS)) {
    const { source } = LANGS[lang];
    const { intro, sections } = parseGuide(guides[lang], source);
    const dir = `sections/${lang}`;
    files.set(`${dir}/README.md`, renderIndex(lang, intro, sections));
    sections.forEach((s, n) => {
      const nav = renderNav(lang, n);
      // Exercises bring their own data and the cheat sheet has no examples.
      const note = n < SLUGS.length - 2 ? [`> ${LANGS[lang].tables}`, ''] : [];
      files.set(`${dir}/${s.slug}.md`, [header(source), '', nav, '', ...note, s.body, '', '---', '', nav, ''].join('\n'));
    });
  }
  return files;
}

// Everything under sections/ that the generator doesn't produce, as repo-relative
// paths (folders end in "/"): `files` can be deleted safely, `folders` are only reported.
function strayEntries(files, root) {
  const stray = { files: [], folders: [] };
  const sectionsDir = path.join(root, 'sections');
  if (!existsSync(sectionsDir)) return stray;
  for (const top of readdirSync(sectionsDir, { withFileTypes: true })) {
    if (!top.isDirectory() || !(top.name in LANGS)) {
      (top.isDirectory() ? stray.folders : stray.files).push(`sections/${top.name}${top.isDirectory() ? '/' : ''}`);
      continue;
    }
    for (const entry of readdirSync(path.join(sectionsDir, top.name), { withFileTypes: true })) {
      const rel = `sections/${top.name}/${entry.name}`;
      if (entry.isDirectory()) stray.folders.push(`${rel}/`);
      else if (!files.has(rel)) stray.files.push(rel);
    }
  }
  stray.files.sort();
  stray.folders.sort();
  return stray;
}

export function writeFiles(files, root) {
  const { files: removed, folders: kept } = strayEntries(files, root);
  for (const f of removed) unlinkSync(path.join(root, f));
  for (const [file, content] of files) {
    mkdirSync(path.dirname(path.join(root, file)), { recursive: true });
    writeFileSync(path.join(root, file), content);
  }
  return { written: [...files.keys()], removed, kept };
}

export function checkFiles(files, root) {
  const stale = [];
  const missing = [];
  for (const [file, content] of files) {
    const target = path.join(root, file);
    if (!existsSync(target)) missing.push(file);
    else if (readFileSync(target, 'utf8').replaceAll('\r\n', '\n') !== content) stale.push(file);
  }
  const stray = strayEntries(files, root);
  const extra = [...stray.files, ...stray.folders].sort();
  return { stale: stale.sort(), missing: missing.sort(), extra };
}

function main(args) {
  const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
  const guides = Object.fromEntries(
    Object.entries(LANGS).map(([lang, t]) => [lang, readFileSync(path.join(root, t.source), 'utf8')]),
  );
  const files = renderAll(guides);

  if (args.includes('--check')) {
    const result = checkFiles(files, root);
    const problems = Object.entries(result).flatMap(([kind, list]) => list.map((f) => `${kind}: ${f}`));
    if (problems.length) {
      console.error(`sections/ is out of date. Run: npm run build:sections\n${problems.join('\n')}`);
      process.exit(1);
    }
    console.log('sections/ is up to date');
    return;
  }

  const { written, removed, kept } = writeFiles(files, root);
  console.log(`Wrote ${written.length} files, removed ${removed.length}`);
  if (kept.length) console.warn(`Not generated, left in place (remove by hand):\n${kept.join('\n')}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  main(process.argv.slice(2));
}
